feat(webapp): UI for smart contract integration
edenia/eden-spend-explorer pull request #206
Opened 2022-11-02 02:43 UTC by warnerHurtado

### UI for smart contract integration 

### What does this PR do?

- Resolve #178

### Steps to test

1. run the project and open localhost:3000 in your browser
2. click on spend tools and see the new features

#### CheckList

- [X] Follow proper Markdown format
- [X] The content is adequate
- [X] The content is available in both english and spanish
- [X] I Ran a spell check

2022-11-03 15:55 UTC, tetogomez requested changes
Please check the comments

2022-11-03 15:55 UTC, tetogomez commented on webapp/src/hooks/customHooks/useForm.js
> +      setErrors({ ...newErrors })
add a blank space before this line

2022-11-03 15:55 UTC, tetogomez commented on webapp/src/hooks/customHooks/useForm.js
> +    Object.keys(form).forEach(key => {
add a blank space before this line

2022-11-03 15:55 UTC, tetogomez commented on webapp/src/hooks/customHooks/useForm.js
> +        formErrors = { ...newErrors }
add a blank space before this line

2022-11-03 15:55 UTC, tetogomez commented on webapp/src/hooks/customHooks/useForm.js
> +    return formErrors
add a blank space before this line

2022-11-03 15:55 UTC, tetogomez commented on webapp/src/hooks/customHooks/useSpendToolsState.js
> +import { useEffect, useState } from 'react'
please reorder those imports by groups

2022-11-03 15:55 UTC, tetogomez commented on webapp/src/hooks/customHooks/useSpendToolsState.js
> +    const transaction = {
add a blank space before this line

2022-11-03 15:55 UTC, tetogomez commented on webapp/src/hooks/customHooks/useSpendToolsState.js
> +  }, [categorizedTxData])
Why this useEffect has `categorizedTxData` as a dependency but never used?

the dependency should be `claimedTxData`

2022-11-03 15:55 UTC, tetogomez commented on webapp/src/routes/SpendTools/index.js
> +import { IconButton, MenuItem, Modal, TextField, Tooltip } from '@mui/material'
Try to use one level MUI import just for consistency 

in order to maintain the performance the idea is to use the top-level import

please check it: https://mui.com/material-ui/guides/minimizing-bundle-size/#option-one-use-path-imports

2022-11-03 15:55 UTC, tetogomez commented on webapp/src/routes/SpendTools/styles.js
> +    '& .css-1d3z3hw-MuiOutlinedInput-notchedOutline': {
I'm pretty sure if You use the correct MUI class you don't need to write that long css classes

example: 
`.MuiOutlinedInput-notchedOutline`

2022-11-03 15:55 UTC, tetogomez commented on webapp/src/routes/SpendTools/styles.js
> +    '& .css-1exfphm-MuiButtonBase-root-MuiButton-root': {
same here

2022-11-03 15:55 UTC, tetogomez commented on webapp/src/routes/SpendTools/styles.js
> +    '& .css-1exfphm-MuiButtonBase-root-MuiButton-root:hover': {
and here

2022-11-03 15:55 UTC, tetogomez commented on webapp/src/utils/format-with-thousand-separator.js
> +  const comma = newValue.toString().split('.')
REMEMBER blank space after const declaration

2022-11-04 00:10 UTC, xavier506 approved these changes
LGTM

2022-11-04 00:10 UTC, merged