feat(webapp): improve homepage
edenia/eden-spend-explorer pull request #207
Opened 2022-11-02 17:31 UTC by warnerHurtado

### Improve homepage

### What does this PR do?

- Resolve #198 

### Steps to test

1. run the project and open localhost:3000 in your browser
2. click on home in the sidebar and see the new features

#### CheckList

- [X] Follow proper Markdown format
- [X] The content is adequate
- [X] The content is available in both english and spanish
- [X] I Ran a spell check

2022-11-02 17:51 UTC, JAMares approved these changes
LGTM

2022-11-02 18:40 UTC, xavier506 commented on webapp/src/routes/Home/index.js
> +          <span className={classes.titleStyles}>Eden Expend Explorer</span>
Eden **Spend** Explorer

2022-11-02 18:40 UTC, xavier506 requested changes
See comment

2022-11-03 00:47 UTC, xavier506 approved these changes
LGTM

2022-11-03 15:59 UTC, tetogomez requested changes
check the comments

2022-11-03 15:59 UTC, tetogomez commented on webapp/src/routes/Home/index.js
> +
remove this black space

2022-11-03 15:59 UTC, tetogomez commented on webapp/src/routes/Home/index.js
> +        <div>
is this `div` necessary?

2022-11-03 15:59 UTC, tetogomez commented on webapp/src/routes/Home/styles.js
> +    '& .css-1exfphm-MuiButtonBase-root-MuiButton-root:hover': {
long classes wrong

2022-11-04 00:09 UTC, merged