Feat/Update, footer, sidebar and header design 97
edenia/eden-spend-explorer pull request #210
Opened 2022-11-03 21:12 UTC by JAMares

### Update

### What does this PR do?

- Resolve #97 
- Resolve #189 
- Resolve #98 

### Steps to test

1. Run Project

#### CheckList

- [X] Follow proper Markdown format
- [X] The content is adequate
- [X] The content is available in both english and spanish
- [X] I Ran a spell check

2022-11-05 01:13 UTC, leisterfrancisco commented
this PR looks kind of big, please, for future PRs, try to split your code into small PRs to make it easier to review.

2022-11-05 01:14 UTC, leisterfrancisco requested changes

2022-11-05 01:14 UTC, leisterfrancisco commented on webapp/src/routes/index.js
> +// const Help = lazy(() => import('./Help'))
is it required?

2022-11-05 01:14 UTC, leisterfrancisco commented on webapp/src/routes/index.js
> +  // },
do we need this?

2022-11-07 14:08 UTC, AngeloCG97 commented on webapp/src/routes/index.js
> +  // },
Yes, I tolken with Josue about this

2022-11-07 14:14 UTC, leisterfrancisco commented
Is this PR still in `WIP`?

2022-11-07 14:26 UTC, AngeloCG97 commented
> Is this PR still in `WIP`?

No

2022-11-07 15:57 UTC, warnerHurtado approved these changes
LGTM

2022-11-07 16:37 UTC, tetogomez approved these changes
LGTM

2022-11-07 17:30 UTC, leisterfrancisco approved these changes

2022-11-07 17:30 UTC, merged