Fix/dont data on delegate level1
edenia/eden-spend-explorer pull request #262
Opened 2022-11-24 16:02 UTC by JAMares

### Fix/dont data on delegate level1

### What does this PR do?

- Resolve #248
- Resolve #248

### Steps to test

1. Run project
2. Enter to Delegate view

#### CheckList

- [X] Follow proper Markdown format
- [X] The content is adequate
- [X] The content is available in both english and spanish
- [X] I Ran a spell check

2022-11-24 16:08 UTC, AngeloCG97 requested changes

2022-11-24 16:08 UTC, AngeloCG97 commented on docker-compose.yaml
> +      # HASURA_GRAPHQL_ADMIN_SECRET: '${HASURA_GRAPHQL_ADMIN_SECRET}'
We should'n comment this vars

2022-11-24 16:08 UTC, AngeloCG97 commented on hapi/src/services/delegate-frontend.service.js
> +  return dataFound
Please add space before return

2022-11-24 16:08 UTC, AngeloCG97 commented on hapi/src/services/delegate-frontend.service.js
> +      if (posDelegate) {
Please add space before and after if and return

2022-11-27 15:49 UTC, xavier506 commented on webapp/src/language/en.json
> +    "invalidEdenMember": "Invalid user, this is't Eden member"
Invalid user, this account isn't an Eden member

2022-11-28 14:34 UTC, AngeloCG97 approved these changes
LGTM

2022-11-28 14:44 UTC, xavier506 approved these changes
LGTM

2022-11-28 14:44 UTC, merged